name: mcp-tools-server
services:
  tavily-mcp:
    build:
      context: ./tavily-mcp/
      dockerfile: Dockerfile
    image: tavily-search-mcp
    container_name: tavily-mcp
    ports:
      - "2400:3000"  # Adjust the ports as necessary based on your app's requirements
    environment:
      - TAVILY_API_KEY=your-tavily-api-key  # Set any necessary environment variables here
